# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infolog_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="infolog",
            name="replay_gameID",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
