# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-07 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infolog_upload', '0002_infolog_replay_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolog',
            name='replay_gameID',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
