# Generated by Django 3.0.2 on 2020-01-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infolog_upload', '0003_auto_20161107_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolog',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low: No hurry.'), ('Normal', 'Normal (default): A developer should look at this.'), ('High', 'High: Game is unplayable!')], default='Normal', max_length=32),
        ),
    ]
